### ISSUE TITLE
deal with the multiple fiber regions assertion in neurophotometrics copier

### ISSUE THREAD

**Issue by grg2rsr** [int-brain-lab/ibl-photometry#58]

**Comment by grg2rsr** [comment]
this is the updated assertion currently in place
```
assert len(rois) == len(locations), 'The number of ROIs and locations must be the same.'
assert len(set(rois)) == len(rois), 'duplicate rois are not possible'
band = 'G' if any([roi.startswith('G') for roi in rois]) else 'R'
ix = [i for i, roi in enumerate(rois) if roi.startswith(band)]
locations = [locations[i] for i in ix]
assert len(set(locations)) == len(locations), 'duplicate brain regions are not possible'
```

**Comment by grg2rsr** [comment]
updated assertion

```
rois = ["G0", "G1", "R0", "R1"]
locations = ["VTA", "SNc", "VTA", "SNc"]

# assert compatible shapes
assert len(rois) == len(locations), "The number of ROIs and locations must be the same."
assert len(set(rois)) == len(rois), "duplicate rois are not possible"

# assert each location being sampled at max twice and if so, by different bands
for location in set(locations):
    ix = [i for i, loc in enumerate(locations) if loc == location]
    assert len(ix) == 2, "there are only 2 possible bands"
    rois_per_loc = [rois[i] for i in ix]
    # check that each band is present only once
    assert sum(True for roi in rois_per_loc if roi.startswith("G")) == 1, (
        "duplicate green band"
    )
    assert sum(True for roi in rois_per_loc if roi.startswith("R")) == 1, (
        "duplicate red band"
    )
```

**Comment by grg2rsr** [comment]
a valid example:
```
neurophotometrics:
    fibers:
    - roi: G0
        location: VTA
    - roi: G1
        location: DR
    - roi: R0
        location: VTA
    - roi: R1
        location: DR
    collection: raw_photometry_data
    sync_channel: 1
    datetime: 2024-09-19T14:13:18.749259
    sync_mode: bpod
```
